INSERT INTO perks (name,description,sourcebook_id,level_req,ranks,rank_range,reqs,limits) VALUES ('Action Boy/Girl','Additional major action does not increase difficulty','1','1','1','1','[]','[]'),
('Adamantium Skeleton','Damage required for crit +1','1','1','3','3','["endurance: 7"]','[]'),
('Adrenaline Rush','If HP<max, STR=10 for skills/melee','1','1','1','1','["strength: 7"]','[]'),
('Animal Friend','1: Mammals, Lizards and Insects roll 1CD on attack; non-effect means no attack. 2: CHA+Survival(2) as major action to befriend non-Mighty/Legendary','1','1','2','5','["charisma: 6"]','[]'),
('Aquaboy/Aquagirl','1: No more rad damage from swimming and double held breath 2: +2 difficulty to detect while underwater','1','1','2','3','["endurance: 5"]','[]'),
('Armorer','Unlock the equivalent rank of mods.','1','1','4','4','["strength: 5","intelligence: 6"]','[]'),
('Awareness','Aim at close range adds +1 Piercing','1','1','1','1','["perception: 7"]','[]'),
('Barbarian','Your DR increases with Melee Damage (STR 7-8=+1, 9-10=+2, 11+=+3)','1','4','1','1','["strength: 7"]','[]'),
('Basher','Gun bash gains Vicious','1','1','1','1','["strength: 6"]','[]'),
('Better Criticals','When you damage, spend Luck to crit','1','1','1','1','["luck: 9"]','[]'),
('Big Leagues','Two-handed melee gains Vicious','1','1','1','1','["strength: 8"]','[]'),
('Black Widow/Lady Killer','Pick a gender. Against that gender, reroll 1d20 on CHA and +1CD damage.','1','1','1','1','["charisma: 6"]','[]'),
('Blacksmith','Unlock the equivalent rank of mods.','1','2','3','4','["strength: 6"]','[]'),
('Blitz','1: Reroll 1d20 on attack when close in and melee in one turn. 2: +1CD on that attack.','1','1','2','3','["agility: 9"]','[]'),
('Bloody Mess','Roll 1CD when crit; effect=+1 crit.','1','1','1','1','["luck: 6"]','[]'),
('Can Do!','Find 1 more food while scavenging.','1','1','1','1','["luck: 5"]','[]'),
('Cap Collector','Buy/sell prices 10% more favorable.','1','1','1','1','["charisma: 5"]','[]'),
('Cautious Nature','Reroll 1d20 when buying more d20s with AP.','1','1','1','1','["perception: 7"]','["no Daring Nature perk"]'),
('Center Mass','Choosing torso does not raise difficulty. Reroll 1d20.','1','1','1','1','["agility: 7"]','[]'),
('Chem Resistant','1: -1CD to determine addiction. 2: Cannot become addicted to chems.','1','1','2','4','["endurance: 7"]','[]'),
('Chemist','Chems you make last twice as long. Unlocks chem recipes.','1','1','1','1','["intelligence: 7"]','[]'),
('Commando','+1CD/rank to fire rate 3+ weapon.','1','2','2','3','["agility: 8"]','[]'),
('Comprehension','Roll 1CD to extend magazine bonus.','1','1','1','1','["intelligence: 6"]','[]'),
('Concentrated Fire','Reroll 3CD when you spend ammo to increase damage','1','1','1','1','["perception: 8","agility: 6"]','[]'),
('Daring Nature','Reroll 1d20 when buying more d20s with GM AP','1','1','1','1','["luck: 7"]','["no Cautious Nature perk"]'),
('Demolition Expert','Blast weapons gain Vicious. Unlocks explosives recipes.','1','1','1','1','["perception: 6","luck: 6"]','[]'),
('Dodger','1: Defend difficulty -1. 2: -1AP cost to increase defense.','1','4','2','6','["agility: 6"]','[]'),
('Dogmeat','You have a pet dog.','1','1','1','1','["charisma: 5"]','[]'),
('Entomologist','+1 Piercing against Insects.','1','1','1','1','["intelligence: 7"]','[]'),
('Fast Metabolism','Non-rest healing +1/rank','1','1','3','3','["endurance: 6"]','["robot"]'),
('Faster Healing','First d20 END+Survival to heal self is free (maximum still 5d20).','1','1','1','1','["endurance: 6"]','["robot"]'),
('Finesse','Reroll all CD once/combat for free','1','1','1','1','["agility: 9"]','[]'),
('Fortune Finder','+3CDc while looting; +6CDc; +10CDc','1','2','3','4','["luck: 5"]','[]'),
('Ghost','First d20 AGI+Sneak in dark is free (maximum still 5d20).','1','1','1','1','["perception: 5","agility: 6"]','[]'),
('Grim Reaper’s Sprint','Roll 1CD when you kill an enemy. Add 2AP on an effect.','1','1','1','1','["luck: 8"]','[]'),
('Gun Fu','On ranged hit, spend (Rank)AP and (Rank)Ammo to hit (Rank) targets within close range of the first target. Each takes same damage as first.','1','1','3','5','["agility: 10"]','[]'),
('Gun Nut','Unlock the equivalent rank of mods.','1','2','4','4','["intelligence: 6"]','[]'),
('Gunslinger','+(Rank)CD with 1H ranged fire rate 2 or less. Reroll hit location.','1','2','2','4','["agility: 7"]','[]'),
('Hacker','-1 Difficulty to hack.','1','1','1','1','["intelligence: 8"]','[]'),
('Healer','+(Rank) healing with First Aid.','1','1','3','5','["intelligence: 7"]','[]'),
('Heave Ho!','Spend 1AP to increase throw range.','1','1','1','1','["strength: 8"]','[]'),
('Hunter','Vicious against Mutated Mammals, Lizards, and Insects.','1','1','1','1','["endurance: 6"]','[]'),
('Infiltrator','Reroll 1d20 on lockpick.','1','1','1','1','["perception: 8"]','[]'),
('Inspirational','Max group AP +1.','1','1','1','1','["charisma: 8"]','[]'),
('Intense Training','Increase any SPECIAL by 1.','1','2','10','2','[]','[]'),
('Iron Fist','1: +1CD unarmed damage. 2: Unarmed gains Vicious.','1','1','2','5','["strength: 6"]','[]'),
('Junktown Jerky Vendor','CHA+Barter buy/sell difficulty -1','1','1','1','1','["charisma: 8"]','[]'),
('Jury Rigging','Repair without components. Break on next complication (range +1).','1','1','1','1','[]','[]'),
('Laser Commander','+(Rank)CD with energy weapons.','1','2','2','4','["perception: 8"]','[]'),
('Lead Belly','1: Reroll CD to determine rad damage from food or drink. 2: Immune to food/drink rad damage.','1','1','2','4','["endurance: 6"]','[]'),
('Life Giver','Max Health +(END)','1','5','5','5','[]','[]'),
('Light Step','Spend AP to ignore complications for AGI tests. Reroll 1d20 on AGI+ Athletics to avoid floor traps.','1','1','1','1','[]','[]'),
('Master Thief','Difficulty to detect pickpocket +1.','1','1','1','1','["perception: 8","agility: 9"]','[]'),
('Medic','Reroll 1d20 First Aid to treat Inj.','1','1','1','1','["intelligence: 8"]','[]'),
('Meltdown','Kills with energy weapons cause the target to explode. Roll (Damage Rating/2)CD, (effect) creatures in close range take (total damage).','1','1','1','1','["perception: 10"]','[]'),
('Mister Sandman','+2CD on sneak attack with silencer.','1','1','1','1','["agility: 9"]','[]'),
('Moving Target','Sprint = +1 Defense','1','1','1','1','["agility: 6"]','[]'),
('Mysterious Stranger','For 1 Luck Mysterious Stranger may show up during combat (refunded).','1','1','1','1','["luck: 7"]','[]'),
('Nerd Rage!','When health<max/4, +(Rank) physical DR, energy DR, and damage.','1','2','3','5','["intelligence: 8"]','[]'),
('Night Person','-1 difficulties due to darkness.','1','1','1','1','["perception: 7"]','[]'),
('Ninja','Melee/Unarmed sneak attacks +2CD.','1','1','1','1','["agility: 8"]','[]'),
('Nuclear Physicist','Rad weapons inflict +1 Rad/effect','1','1','1','1','["intelligence: 9"]','[]'),
('Pain Train','1: Charge with Power Armor (or as a Super Mutant). Move into reach within Medium range, STR+Athletics(2) unarmed damage+prone. 2: +1CD and Stun.','1','1','2','5','["strength: 9","endurance: 7"]','[]'),
('Paralyzing Palm','Stun when aiming unarmed attack.','1','1','1','1','["strength: 8"]','[]'),
('Party Boy/Girl','Cannot become addicted to alcohol, and heal +2HP drinking alcohol.','1','1','1','1','["endurance: 6","charisma: 7"]','[]'),
('Pathfinder','PER+Survival to halve travel time.','1','1','1','1','["perception: 6","endurance: 6"]','[]'),
('Pharma Farma','Find 1 more chem while scavenging.','1','1','1','1','["luck: 6"]','[]'),
('Pickpocket','1: Ignore first complication from AGI+Sneak to pick or plant. 2: Reroll 1d20 when picking. 3: Difficulty to pick -1.','1','1','3','3','["perception: 8","agility: 8"]','[]'),
('Piercing Strike','Unarmed/Bladed attacks +1 Piercing.','1','1','1','1','["strength: 7"]','[]'),
('Pyromaniac','Fire damage +(Rank)CD.','1','2','3','4','["endurance: 6"]','[]'),
('Quick Draw','Draw weapon/item without action.','1','1','1','1','["agility: 6"]','[]'),
('Quick Hands','2AP to double fire rate.','1','1','1','1','["agility: 8"]','[]'),
('Rad Resistance','Rad DR +(Rank).','1','1','2','4','["endurance: 8"]','[]'),
('Refractor','Energy DR +(Rank).','1','1','2','4','["perception: 6","luck: 7"]','[]'),
('Ricochet','Spend Luck to send complication shot back at enemy.','1','5','1','0','["luck: 10"]','[]'),
('Rifleman','+(Rank)CD with 2H ranged fire rate 2 or less. At 2nd Rank, +1 Piercing.','1','2','2','4','["agility: 7"]','[]'),
('Robotics Expert','Unlock the equivalent rank of mods. 2: Difficulty to repair robots -1. 3: Can reprogram robots.','1','2','3','4','["intelligence: 8"]','[]'),
('Science','Unlock the equivalent rank of mods.','1','2','3','4','["intelligence: 6"]','[]'),
('Scoundrel','Ignore first complication of CHA+Speech to lie.','1','1','1','1','["charisma: 7"]','[]'),
('Scrapper','1: Salvage uncommon materials when scrapping items. 2: Salvage rare materials.','1','3','2','5','[]','[]'),
('Scrounger','1: +3CD ammo when looting. 2: +6CD ammo. 3: +10CD ammo.','1','1','3','5','["luck: 6"]','[]'),
('Shotgun Surgeon','Shotguns gain +1 Piercing.','1','1','1','1','["strength: 5","agility: 7"]','[]'),
('Skilled','Add +2 or +1/+1 to skills.','1','3','10','3','[]','[]'),
('Size Matters','+(Rank)CD to Big Guns attacks.','1','1','3','4','["endurance: 7","agility: 6"]','[]'),
('Slayer','1 Luck to crit with unarmed/melee.','1','1','1','1','["strength: 8"]','[]'),
('Smooth Talker','Reroll 1d20 opposed Barter/Speech.','1','1','1','1','["charisma: 6"]','[]'),
('Snakeater','Poison DR +2.','1','1','1','1','["endurance: 7"]','[]'),
('Sniper','Aim, 2H, Accurate, specify location without increasing difficulty.','1','1','1','1','["perception: 8","agility: 6"]','[]'),
('Solar Powered','Heal 1 Rad/hour in direct sunlight.','1','1','1','1','["endurance: 7"]','[]'),
('Steady Aim','Reroll 2d20 on first or 1d20 on all attacks after Aim.','1','1','1','1','["strength: 8","agility: 7"]','[]'),
('Strong Back','+25lbs carry weight.','1','1','3','2','["strength: 5"]','[]'),
('Tag!','Pick an additional Tag skill.','1','5','1','0','[]','[]'),
('Terrifying Presence','1: Reroll 1d20 on speech to scare. 2: STR+Speech(2) to threaten enemy within Medium range. They must move away from you during next turn.','1','3','2','5','["strength: 6","charisma: 8"]','[]'),
('Toughness','Physical DR +(rank).','1','1','2','4','["endurance: 6","luck: 6"]','[]'),
('All Night Long','Hunger and Thirst do not progress at night; Fatigue every 2 days of starving instead of 1.','3','16','1','0','[]','["Not a Robot"]'),
('Ammosmith','1: Craft ammo rarity 1. 2: Craft ammo rarity 3, and dismantle ammo into 1/2 components. 3: Craft ammo rarity 5; +6-rarityCD ammo, effects double total.','3','2','3','4','["intelligence: 7"]','[]'),
('Bodyguards','Companions gain +1 Phys/Energy DR.','3','5','1','0','["charisma: 8"]','[]'),
('Community Organizer','+(Rank) manned food/defense per day +1CD Hunting, Gathering, and Scavenging.','3','1','3','3','["charisma: 5","endurance: 5"]','[]'),
('Contractor','1: Half materials, half happiness to build (double time to negate happiness loss). 2: Can assign unskilled to build, happiness -1. 3: Can assign person missing perk to build as long as someone has it.','3','2','3','4','["charisma: 5","intelligence: 5"]','[]'),
('Covert Operator','+2CD small guns/energy sneak attack.','3','1','1','0','["agility: 8"]','[]'),
('Enforcer','Target location with shotgun adds Debilitating.','3','12','1','0','["agility: 9"]','[]'),
('Green Thumb','2+2/AP foraging items.','3','4','1','0','["perception: 4"]','[]'),
('Gun Runner','Sprint with 1H gun, 1AP to move one additional zone.','3','4','1','0','["agility: 6"]','[]'),
('Happy Camper','1: If hunger is full or sated, hunger doesn’t degrade at a campfire.','3','3','2','4','["charisma: 7","endurance: 6"]','[]'),
('Hired Help','Gain a companion.','3','1','1','0','["charisma: 7"]','["no companion"]'),
('Home Defense','1: Can craft traps, INT+Repair failure triggers trap. 2: Failure succeeds at cost.','3','5','2','5','["intelligence: 6"]','[]'),
('Homebody','1: Heal (END)CD after 1hr in settlement you belong to. 2: +1/Effect, END+Survival to heal injuries difficulty maximum 2.','3','5','2','5','["endurance: 6"]','[]'),
('Local Leader','1: Establish supply lines. 2: Build stores/crafting tables.','3','2','2','5','["charisma: 6"]','[]'),
('Lock and Load','Big Guns >0 fire rate +(Rank).','3','2','3','4','["strength: 7"]','[]'),
('Mechanical Menace/Class Freak','Pick robots or mutated humans. When they attack, roll 1CD. On non-effect, they don’t attack. Reroll 1d20 for CHA against them.','3','1','1','0','["charisma: 5","intelligence: 5"]','[]'),
('Nocturnal Fortitude','Max/current HP +(END) at night.','3','12','1','0','["endurance: 6"]','["Not a Robot"]'),
('Pannapictagraphist','Reroll book/magazine rolls if you’ve already found the first.','3','1','1','0','["luck: 5"]','[]'),
('Pharmacist','RadAway heals +1+(Rank) Rad damage.','3','2','3','6','["intelligence: 8"]','[]'),
('Photosynthetic','Regenerate (Rank)HP/hr direct sun.','3','5','2','10','["endurance: 7"]','[]'),
('Quack Surgeon','Use alcohol in First Aid to heal 2HP/AP spent. Patient receives effects of beverage.','3','12','1','0','["charisma: 7"]','[]'),
('Rejuvenated','When full, MaxHP+2, reroll 1d20 on STR. When quenched, reroll 1d20 on END, generate 1AP each turn. Full/Quenched last twice as long.','3','12','1','0','["endurance: 7"]','["Not a Robot"]'),
('Retribution','Recover 1HP and 1AP (Rank) rounds per combat encounter.','3','2','3','5','["endurance: 8","luck: 8"]','[]'),
('Robot Wrangler','Gain a robot companion.','3','1','1','0','["intelligence: 5"]','["no companion"]'),
('Squad Maneuvers','1: Maintain hurried pace with CHA+Survival(1) for +1hr. 2: Can spend 1AP to move ally to reach when spending 1AP to move.','3','1','2','3','["charisma: 7"]','[]'),
('Super Duper','Roll (Rank)CD to regain (effects) components when crafting.','3','3','3','4','["luck: 6"]','[]'),
('Taking One for the Team','1: Take damage for ally in same zone (Rank) rounds per combat encounter on non-effect on 1CD. 2: Add (Rank)AP when DR doesn’t reduce damage completely. 3: You and ally reroll 1d20 on (Rank) attacks against target.','3','1','3','4','["endurance: 7","charisma: 6"]','[]'),
('Tinkerer','Reduce difficulty of repairing via first aid to INJ, +1 on self. Tinker for 1hr to +2 max HP for 24hrs or until next INJ.','3','1','1','0','["endurance: 5","intelligence: 5"]','[]'),
('True Friends','1: Roll (reputation)CD to avoid reputation loss on effect. 2: Roll CHA+Speech(3) to increase affinity by 2 instead of 1.','3','1','2','6','["perception: 6","charisma: 6"]','[]'),
('Blocker','DR +(Rank) against melee.','4','1','3','5','["strength: 6"]','[]'),
('Bullet Shield','DR +1+(Rank) when using Big Guns.','4','8','3','6','["strength: 8"]','[]'),
('Gladiator','+(Rank)CD when using 1H melee.','4','2','3','5','["strength: 6"]','[]'),
('Incisor','+(Rank) Piercing on melee.','4','2','2','9','["strength: 6"]','[]'),
('Martial Artist','Can take additional melee atk 1AP.','4','8','1','0','["strength: 6"]','[]'),
('Pack Rat','Junk weighs half as much.','4','1','1','0','["strength: 6"]','[]'),
('Scattershot','Can take another shotgun shot 1AP.','4','10','1','0','["strength: 7"]','[]'),
('Sturdy Frame','Non-power armor weight -(Rank)/4.','4','5','3','8','["strength: 8"]','[]'),
('Archer','+(Rank)CD when using (cross)bows.','4','1','3','7','["perception: 6"]','[]'),
('Bow Before Me','+1 Piercing when using (cross)bows.','4','4','1','0','["perception: 8"]','[]'),
('Butcher’s Bounty','+(Rank)CD meat when butchering.','4','3','3','5','["perception: 8"]','[]'),
('Crack Shot','1: Aim 1H ranged +1 range. 2: Add Accurate to the shot.','4','7','2','7','["perception: 7"]','[]'),
('Fire in the Hole','-1 Difficulty to throw explosives.','4','1','1','0','["perception: 8"]','[]'),
('Glow Sight','+(Rank)CD against Glowing enemies.','4','3','3','8','["perception: 8"]','[]'),
('Night Eyes','Ignore difficulty due to darkness on all checks while hiding.','4','7','1','0','["perception: 8"]','[]'),
('Cannibal','1: You may butcher humans (Diff 0). 2: You may butcher ghouls. 3: You may butcher Super Mutants.','4','1','3','0','["endurance: 8"]','[]'),
('Cola Nut','Double HP for Nuka-Cola.','4','14','1','0','["endurance: 6"]','["Not a Robot"]'),
('Dromedary','Drinks decrease thirst by +1 step.','4','3','1','0','["endurance: 7"]','["Not a Robot"]'),
('Fireproof','+(Rank) Energy DR (Fire or Blast).','4','7','3','7','["endurance: 6"]','[]'),
('Ghoulish','1: Heal 1HP/4Rad damage. 2: Heal 1HP/3Rad damage. 3: Heal 1HP/2Rad damage.','4','7','3','8','["endurance: 9"]','["Not a Ghoul or Robot"]'),
('Ironclad','+(Rank) Energy/Phys DR with armor.','4','5','3','5','["endurance: 7"]','[]'),
('Natural Resistance','No disease from fumes or sleeping.','4','10','1','0','["endurance: 7"]','[]'),
('Radicool','Reroll 1d20 on STR and add 1CD to melee for every (MaxHP)/4 Rad damage you have.','4','12','1','0','["endurance: 6"]','["Not Immune to Rads"]'),
('Revenant','+2CD on attacks after revived.','4','12','1','0','["endurance: 8"]','[]'),
('Slow Metabolizer','Food decrease hunger by +1 step.','4','5','1','0','["endurance: 7"]','["Not a Robot"]'),
('Thirst Quencher','No disease from dirty water.','4','6','1','0','["endurance: 7"]','[]'),
('Vaccinated','No disease from claws or bites from Mammals, Lizards, or Insects.','4','16','1','0','["endurance: 7"]','[]'),
('Bloodsucker','Double healing from all blood packs and decrease thirst. 1CD for radiation from Irradiated Blood.','4','11','1','0','["charisma: 6"]','[]'),
('Responder','Wake after First Aid stabilize in combat doesn’t cost AP, heal 2*Rank HP at the start of next turn.','4','9','3','7','["charisma: 8","intelligence: 7"]','[]'),
('Field Surgeon','Heal 3HP/AP when using Stimpak with First Aid. Heal +1 Rad w/ RadAway.','4','15','1','0','["charisma: 8","intelligence: 8"]','[]'),
('Happy Go Lucky','+(Rank)LCK Points w/ first alcohol.','4','17','2','6','["charisma: 9"]','[]'),
('Healing Hands','Heal (Medicine)Rad when First Aid stabilize in combat.','4','18','1','0','["charisma: 8","intelligence: 7"]','[]'),
('Overly Generous','When Rads>=(MaxHP)/4, melee attacks become Radioactive.','4','12','1','0','["charisma: 7"]','["Not Immune to Rads"]'),
('Spiritual Healer','1: Heal Self (Rank)HP when First Aid stabilize in combat. 2: Heal (Rank)HP next turn. 3: Heal (Rank)HP turn after.','4','6','3','9','["charisma: 7"]','[]'),
('Suppressor','1AP to suppress attacked enemy for 1 turn (-(Rank)CD damage)','4','10','3','10','{"charisma: 6"}','{}'),
('Tenderizer','1AP to make vulnerable attacked enemy for 1 turn (+(Rank)CD damage).','4','8','3','10','{"charisma: 7"}','{}'),
('Licensed Plumber','Pipe Weapons lose Unreliable.','4','5','1','0','["intelligence: 6"]','[]'),
('Power Patcher','Repair +1+(Rank) Power Armor HP.','4','5','3','7','["intelligence: 6"]','[]'),
('Power User','1: +3 charges in fusion cores. 2: +6 charges. 3: +10 charges.','4','10','3','10','["intelligence: 9"]','[]'),
('Stabilized','Reroll 1d20 and +1 Piercing on Big Guns while wearing Power Armor.','4','16','1','0','["intelligence: 7"]','[]'),
('Born Survivor','Auto-Stimpak (Rank)x per scene when health below (MaxHP)/4','4','3','3','8','["agility: 8"]','[]'),
('Dead Man Sprinting','+1 Zone on Sprint if <(MaxHP)/2.','4','8','1','0','["agility: 7"]','[]'),
('Escape Artist','Hide in combat if no LoS with AGI+ Sneak(#enemies in Medium Range), and Sprint doesn’t reduce difficulty to detect.','4','15','1','0','["agility: 8"]','[]'),
('Evasive','Your DR increases like Melee damage (AGI 7-8=+1, 9-10=+2, 11+=+3).','4','7','1','0','["agility: 7"]','[]'),
('Goat Legs','+(Rank)*2 DR against fall damage.','4','7','3','5','["agility: 7"]','[]'),
('Modern Renegade','Hit 1H ranged w/o aim adds +(Rank) AP, which cannot be saved.','4','8','3','5','["agility: 7"]','[]'),
('Secret Agent','Stealth Boys last +(Rank) turns.','4','7','3','5','["agility: 9"]','[]'),
('Dry Nurse','Roll 1CD on First Aid to Stabilize with Stimpak, Effect=keep Stimpak.','4','13','1','0','["luck: 8"]','[]'),
('Junk Shield','+1 Physical and Energy DR per 5 junk, max (Rank) DR.','4','1','3','8','["luck: 7"]','[]'),
('Mysterious Savior','For 1 Luck Mysterious Savior may stabilize you (refunded).','4','1','1','0','["luck: 7"]','[]'),
('Psychopath','On kill (Rank)CD, Effect=+Luck.','4','11','3','6','["luck: 8"]','[]'),
('Serendipity','If HP<(MaxHP)/3, spend 1 Luck when attacked before attack roll to make attack miss (Rank) times per scene.','4','5','3','6','["luck: 7"]','[]'),
('Storm Chaser','When rain/rad storm, heal 1HP each turn in combat, (LCK)/2HP per hour outside combat.','4','15','1','0','["luck: 6"]','[]'),
('Ammo Factory','Double ammo production','4','5','1','1','[Book]','[]'),
('Arms Breaking','Spend 3-rank AP to break target’s wielded weapon after successful melee as Super Mutant or in Power Armor','4','7','3','6','[Book]','[]'),
('Blood Sacrifice!','+rank Physical and Energy DR and heal 2+2*rank HP to whole party when reduced to 0HP','4','6','3','6','[Book]','[]'),
('Botany Buddy','Spend 1 Luck point to regain 4HP and +2 Physical DR until end of next scene when foraging','4','6','1','1','[Book]','[]'),
('Brawling Chemist','Learn recipe for Super Chem Mk I, which is viable 3*2^rank hours after creation','4','11','3','5','[Book]','[]'),
('Collateral Damage','Spend 1 Luck point to make enemy killed with melee explode (meleeCD/2 CD does damage total to effect enemies in close range of killed enemy)','4','9','1','1','[Book]','[]'),
('Detonation Contagion','Spend 1 Luck point to make enemy killed with explosive explode (explosiveCD/2 CD does damage total to effect enemies in close range of killed enemy)','4','9','1','1','[Book]','[]'),
('Electric Absorption','Spend 1 Luck point to absorb Energy damage as Robot or Power Armor rank times per scene (heals effects HP to location and adds 1 charge to power armor fusion core)','4','9','3','9','[Book]','[]'),
('Exploding Palm','Spend 1AP on successful Unarmed to cause 2+rankCD damage to effects enemies in close range of target','4','9','3','9','[Book]','[]'),
('Far-Flung Fireworks','Spend 1 Luck point to make enemy killed with ranged explode (rangedCD/2 CD does damage total to effect enemies in close range of killed enemy)','4','9','1','1','[Book]','[]'),
('Follow-Through','+rankCD damage on every attack against target of successful ranged sneak attack','4','8','3','8','[Book]','[]'),
('Funky Duds','+5/8/10 Poison DR if wearing complete set of armor','4','7','3','7','[Book]','[]'),
('Hack and Slash','Spend AP to deal damage from successful melee attack to rank additional enemies (AP=total Def of enemies but -1 AP each at rank 3)','4','8','3','8','[Book]','[]'),
('Master Infiltrator','Spend 1 Luck point to auto-succeed Lockpick or Hack of rank difficulty','4','8','3','8','[Book]','[]'),
('Nuclear Proliferator','Learn recipe for Lightweight Mini-Nuke, which is viable 3*2^rank hours after creation','4','11','3','6','[Book]','[]'),
('Power Armor Reboot','Spend 1 Luck point to regain all HP and half power armor HP once per day when reduced to 0HP in power armor','4','10','1','1','[Book]','[]'),
('Power Sprinter','-2 Difficulty to run through difficult terrain or over obstacles in power armor (min 0)','4','8','1','1','[Book]','[]'),
('Retribution','+1+rank HP and rank AP when enemy misses after Defend','4','12','3','6','[Book]','[]'),
('Sizzling Style','+5 Energy DR against fire if wearing complete set of armor','4','7','1','1','[Book]','[]'),
('Survival Shortcut','Learn recipe for Survival Syringe, which is viable 3*2^rank hours after creation','4','11','3','5','[Book]','[]'),
('What Rads?','+5 Radiation DR, Heal +1 radiation damage when heal 1+ HP','4','9','1','1','[Book]','[]');