theme_index=4
db_path="C:\\Users\\owner\\2d20-fallout-character-builder-rust\\target\\debug\\fallout_2d20.db"
font_path=Some("C:\\Users\\owner\\2d20-fallout-character-builder-rust\\target\\debug\\fonts/Monofonto.ttf")
font_size=20
crt_distortion=0.031
crt_scanline_strength=0.024
crt_vignette_multiplier=16.856
crt_vignette_exponent=0.197
crt_roll_speed=0.057
crt_tint_strength=0.041
crt_chromatic_aberration=0.0004
