INSERT INTO armor_legendary (name,eff,head_roll,arm_roll,torso_roll,leg_roll) VALUES
('Acrobat’s','-Half fall damage (2 pieces = 0 fall damage)','0','0','0','1'),
('Assassin’s','+2 PhDR and EnDR from non-mutated humans','1','1','1','2'),
('Auto Stim','Automatically take one Stimpak the moment HP goes below ¼ once per scene','0','0','2','0'),
('Bolstering','+2 PhDR and EnDR at 1/2 HP, +3 at 1/4 HP','0','0','3','0'),
('Cavalier’s','+2 PhDR after Defend or Sprint','0','2','0','0'),
('Chameleon','+1 Difficulty to spot while hidden and unmoving','0','0','4','0'),
('Champion','Set 1d20 to 1 on STR or END test once per scene','0','3','0','0'),
('Cloaking','Invisible (like stealth boy) once per scene after hit by melee','2','4','5','3'),
('Cryogenic','+1 complication range to enemy melee, #CD CD Freeze Energy on complication','3','5','6','4'),
('Cunning','Set 1d20 to 1 on AGI or PER test once per scene','4','0','0','5'),
('Duelist’s','+1 complication range to enemy melee, disarm on complication','5','6','7','6'),
('Exterminator’s','+2 PhDR and EnDR from insects, arachnids, or mirelurks','6','7','8','7'),
('Ghoul Slayer’s','+2 PhDR, EnDR, and RadDR from ghouls','7','8','9','8'),
('Hunter’s','+2 PhDR and EnDR from mammals or lizards','8','9','10','9'),
('Incendiary','+1 complication range to enemy melee, #CD CD Persistent Energy on complication','9','10','11','10'),
('Lucky','Set 1d20 to 1 or CD to effect once per day when spending Luck points to re-roll','10','11','12','11'),
('Martyr’s','-1AP cost to take additional actions when at 1/4 HP (does not stack with others)','11','12','13','12'),
('Mutant Slayer’s','+2 PhDR and EnDR from super mutants','12','13','14','13'),
('Poisoner’s','+4 PoiDR','13','14','15','14'),
('Powered','+1AP each turn','14','15','0','15'),
('Punishing','Enemy effect results inflict 1 Dam back at enemy','0','0','16','16'),
('Rad Powered','Set 1d20 to 1 on STR test once per 5 Rad damage per scene','15','16','17','17'),
('Safecracker’s','Set 1d20 to 1 on Lockpicking once per scene','0','17','0','0'),
('Sentinel’s','+3 PhDR and EnDR if you did not move last turn','0','18','0','0'),
('Sharp','Set 1d20 to 1 on INT or CHA test once per scene','16','19','18','18'),
('Sprinter’s','-1AP cost to cross difficult terrain or obstacles (min 0)','17','0','0','19'),
('Troubleshooter’s','+2 PhDR and EnDR from robots','18','20','19','20'),
('Unyielding','Re-roll 1d20 on any test while at ¼ HP','0','0','20','0');