INSERT INTO dam_effects (name,description) VALUES
('Burst','The attack may hit one additional target within Close range of the primary target for each Effect rolled. Each additional target costs 1 additional shot from the weapon.'),
('Breaking','For each Effect rolled, reduce the number of Cover Dice a piece of cover provides by 1, permanently. If the target is not in cover, instead reduce the damage resistance on the location struck by 1, according to the damage type of the weapon (i.e., physical damage reduces Physical damage resistance, energy damage reduces Energy damage resistance).'),
('Persistent','If one or more Effects are rolled, the target suffers the weapon’s damage again at the end of their next and subsequent turns, for a number of rounds equal to the number of Effects rolled. A character may spend a major action to make a test to stop Persistent damage early; the difficulty is equal to the number of Effects rolled, and the attribute + skill used are chosen by the GM. Some Persistent weapons may inflict a different type of damage to the weapon, and where this is the case, it is noted in brackets; for example, Persistent (Poison).'),
('Piercing X','Ignore X points of the target’s damage reduction for each Effect rolled, where X is the rating of this damage effect.'),
('Radioactive','For every Effect rolled, the target also suffers 1 point of Radiation damage. This Radiation damage is totaled and applied separately, after a character has suffered the normal damage from the attack.'),
('Spread','For each Effect rolled, your attack inflicts one additional hit on the target. Each additional hit inflicts half the rolled damage (round down) and hits a random location even if a specific location was targeted for the initial attack.'),
('Stun','If one or more Effects are rolled, the target loses their normal actions in their next turn. A stunned character or creature may still spend AP to take additional actions as normal.'),
('Vicious','The attack inflicts +1 damage for each Effect rolled.'),
('Arc','Each Effect rolled automatically hits one additional target within close range of the primary target. Each additional target suffers half the rolled damage. Unlike burst, this does not cost additional ammunition.'),
('Freeze','Enemies hit by this attack will be Frozen if the number of Effects rolled are equal or more than half the target’s END (or half the target’s BODY for Creatures). A Frozen creature cannot take actions on its next turn');