INSERT INTO gear (name,eff,wgt,cost,rarity,sourcebook_id) VALUES
('Large Backpack','["+10*STR carry weight"]','0','60','2','1'),
('Small Backpack','["+5*STR carry weight"]','0','30','1','1'),
('Bobby Pin','["-1 Diff on Lockpick (min 1)"," breaks 1/complication"]','0','1','0','1'),
('Deluxe Toolkit','["-1 Diff on Repair (min 0)","+1 Diff on Repair on tests that normally require a workbench"]','20','150','3','1'),
('Doctor’s Bag','["-1 Diff on Medicine (min 0)"," +2 patients for long term care"]','10','300','3','1'),
('Electronic Lockpicker','["-2 Diff on Lockpick (min 0)"," ignores first complication"," breaks on 2+ simultaneous complications"]','4','375','4','1'),
('First Aid Kit','["+2HP healed on First Aid action"]','4','200','2','1'),
('Flashlight','["Bright light in any one zone within medium range"]','2','100','3','1'),
('Geiger Counter','["PER+Survival(1) to determine if and how much radiation in an area"]','8','325','3','1'),
('Holotags','["Identifies the fallen"]','0','5','2','1'),
('Holotape Player','["Allows playback of audio holotapes"]','3','250','2','1'),
('Lantern','["Bright light in close range"," dim light in medium range"]','3','15','2','1'),
('Lock Pick Set','["-1 Diff on Lockpick (min 0)"," broken on 3 complications"]','2','150','2','1'),
('Multi-Tool','["-1 Diff on Repair (min 0)"]','1','100','2','1'),
('Pack Brahmin','["Carries heavy loads"," produces milk"," produces fertilizer"]','0','200','3','1'),
('Pip-Boy','["Add holotape reader"," add radio"," add geiger counter"," add flashlight"," ignore difficulty increase for targeting when using VATS"]','0','0','0','1'),
('Radio','["Picks up and plays radio transmissions"]','2','75','2','1'),
('Signal Flare','["bright light in close range until end of current scene (single use)"]','0','10','1','1'),
('Torch','["bright light in close range until end of current scene"," INT+Survival(1+X) to light (X=number of previous uses)"]','1','10','1','1');