INSERT INTO weapon_legendary (roll_table,name,eff,sg_roll,ew_roll,bg_roll,mw_roll,u_roll) VALUES
('1','Assassin’s','Vicious against non-mutated humans, or +2 Dam/effect if already Vicious','1','1','1','1','1'),
('1','Berserker’s','+(6-TorsoPhDR)CD (min 0)','0','0','0','2','2'),
('1','Blazing','4CD Persistent Energy Dam if enemy misses melee after Defend action','0','0','0','3','0'),
('1','Bloodied','+1CD for every 1/4 health (under full = 1)','0','0','0','4','3'),
('1','Cavalier’s','+2CD when Defend or Sprint','0','0','0','5','4'),
('1','Charged','4CD Stun Energy Dam if enemy misses melee after Defend action','0','0','0','6','0'),
('1','Crippling','Injury to arm/leg at 4 Dam','2','2','2','7','5'),
('1','Deadeye','-1AP cost for minor and major actions after Aim action (does not stack with others)','3','3','3','0','0'),
('1','Defiant','+2CD if spend max fire rate and declare empty (requires reload)','4','4','4','0','0'),
('1','Duelist’s','Disarm if effect on 1CD when enemy misses after Defend','0','0','0','8','6'),
('1','Enraging','Spend 1 Luck point to force enemy to attack nearest enemy for rest of scene after successful hit','5','5','5','9','7'),
('1','Explosive','Hit +1 target (chosen by GM and first within reach) for every effect rolled (half damage) (does not stack with Arc or Burst)','6','0','0','0','0'),
('1','Exterminator’s','Vicious against insects, arachnids, and mirelurks, or +2 Dam/effect if already Vicious','7','6','6','10','8'),
('1','Freezing','Spend 1 Luck point to add Freeze to attack','8','7','7','11','9'),
('1','Frigid','4CD Freeze  Energy Dam if enemy misses melee after Defend action','0','0','0','12','0'),
('1','Furious','+1CD for every additional hit against the same enemy (per scene)','0','0','0','13','10'),
('1','Ghoul Slayer’s','Vicious against ghouls, or +2 Dam/effect if already Vicious','9','8','8','14','11'),
('1','Hitman’s','+1CD after Aim','10','9','9','0','0'),
('1','Hunter’s','Vicious against mammals and lizards, or +2 Dam/effect if already Vicious','11','10','10','15','12'),
('1','Incendiary','Add Persistent (Energy)','12','0','0','0','0'),
('1','Instigating','+3CD against targets with full health','13','11','11','16','13'),
('1','Irradiated','Add Radioactive','14','12','12','17','14'),
('1','Junkie’s','+1CD per addiction','15','13','13','18','15'),
('1','Kneecapper','Injury to leg at 3 Dam','16','14','14','19','16'),
('1','Lucky','Gain 1 Luck point if effect on 1CD after spending Luck points to re-roll dice','17','15','15','20','17'),
('2','Mighty','+2CD','0','0','0','1','1'),
('2','Mutant Slayer’s','Vicious against super mutants, or +2 Dam/effect if already Vicious','1','1','1','2','2'),
('2','Nimble','Move action is free after Aim','2','2','2','0','0'),
('2','Nocturnal','Vicious at night, or +2 Dam/effect if already Vicious','3','3','3','3','3'),
('2','Penetrating','Add Piercing 2','4','4','4','4','4'),
('2','Plasma Infused','+2CD and both physical and energy damage','5','0','0','0','0'),
('2','Poisoner’s','Add Persistent (Poison)','6','5','5','5','5'),
('2','Powerful','+2CD','7','6','6','0','0'),
('2','Quickdraw','Draw Item action is free','8','7','7','6','6'),
('2','Rapid','+3 rate','9','8','8','0','0'),
('2','Relentless','Spend 1 Luck point to regain AP spent on attack that inflicts crit','10','9','9','7','7'),
('2','Sentinel’s','+2 (+3 if Parry) PhDR and EnDR if did not move last turn','0','0','0','8','8'),
('2','Staggering','Add Stun','11','10','10','9','9'),
('2','Stalker’s','Count 1d20 as a 1 if sneak attack and only Aim action','12','11','11','0','0'),
('2','Steadfast','+2 PhDR after Aim','13','12','12','0','0'),
('2','Troubleshooter’s','Vicious against robots, or +2 Dam/effect if already Vicious','14','13','13','10','10'),
('2','Two-Shot','+2CD, Add Vicious, Add Ammo-Hungry','15','14','14','0','0'),
('2','Violent','+2CD, Injury at 4 Dam, Add Recoil(7) or +1 to Recoil','16','0','0','0','0'),
('2','Wounding','Add Persistent (Physical)','17','15','15','11','11');