INSERT INTO weapon_mods (name,prefix,effects,slot,wgt,cost) VALUES
('Hardened','Hardened','[“+1CD Dam”]','1','0','20'),
('Powerful','Powerful','[“+2CD Dam”]','1','1','25'),
('Advanced','Advanced','[“+3CD Dam”,”+1 Rate”]','1','2','35'),
('Calibrated','Calibrated','[“Gain Vicious”]','1','0','25'),
('Automatic','Auto','[“-1CD Dam”,“+2 Rate”,“Gain Burst”,“Gain Inaccurate”]','1','1','30'),
('Hair Trigger','Hair Trigger','[“+1 Rate”]','1','0','20'),
('.38 Receiver','.38','[“4CD Dam”,“Ammo = .38”]','1','3','20'),
('.308 Receiver','.308','[“7CD Dam”,“Ammo = .308”]','1','4','40'),
('.45 Receiver','.45','[“4CD Dam”,”+1 Rate”,“Ammo = .45”]','1','2','19'),
('.50 Receiver','.50','[“8CD Dam”,”Gain Vicious”,“Ammo = .50”]','1','4','30'),
('Automatic Piston','Automatic','[“+2 Rate”,”-1 Range”]','1','2','75'),
('12.7mm Receiver','12.7mm','[“7CD Dam”,”Gain Vicious”,“Ammo = 12.7mm”]','1','3','50'),
('.357 Receiver','.357','[“4CD Dam”,”Gain Vicious”,”Lose Piercing 1”,“Ammo = .357”]','1','0','20'),
('.45-70 Receiver','.45-70','[“4CD Dam”,”Lose Vicious”,”Gain Piercing 1”,“Ammo = .45-70 Govt”]','1','4','40'),
('Snubnose','Snub-nosed','[“Gain Inaccurate”]','2','-1','0'),
('Bull','Bull Barreled','[“Gain Reliable”]','2','0','10'),
('Long (Small Guns)','Long','[“+1 Range”]','2','1','20'),
('Long (Energy Weapons)','Long','[“Lose Close-Quarters”,”+1 Range”]','2','2','20'),
('Long (Flamer)','Long','[“Lose Inaccurate”]','2','2','28'),
('Long (Junk Jet)','Long','[“+1 Range”]','2','2','20'),
('Ported','Ported','[“+1 Range”,”+1 Rate”]','2','1','35'),
('Vented','Vented','[“+1 Range”,”+1 Rate”,”Gain Reliable”]','2','1','36'),
('Sawed-Off','Sawed-off','[“Lose Two-Handed”,”Gain Close Quarters”]','2','-2','3'),
('Shielded','Shielded','[“+1CD Dam”]','2','0','37'),
('Finned','Finned','[“+1CD Dam”,”+1 Range”]','2','2','15'),
('Bracketed Short','','[“Allows Muzzle mods”]','2','0','6'),
('Splitter','Scattergun','[“-1CD Dam”,”Gain Spread”,”Gain Inaccurate”]','2','1','31'),
('Automatic','Automatic','[“-1CD Dam”,”Lose Close-Quarters”,”+1 Range”,”+1 Rate”]','2','1','24'),
('Bracketed Long','','[“Lose Close-Quarters”,“+1 Range”,”Allows Muzzle mods”]','2','2','25'),
('Improved','Improved','[“+1CD Dam”]','2','1','26'),
('Sniper','Sniper','[“+2CD Dam”,”Lose Close-Quarters”,”+1 Range”,”-1 Rate”]','2','2','30'),
('Flamer','Thrower','[“-2CD Dam”,”+2 Rate”,”Gain Burst”,”Gain Spread”,”Gain Inaccurate”,”-1 Range”]','2','1','35'),
('Charging','Charging','[“+4CD Dam”,”-3 Rate”,”+1 Range”]','2','10','357'),
('Accelerated','High-Speed','[“+1CD Dam”,”+1 Rate”,”-1 Range”]','2','5','45'),
('Tri-Barrel (Minigun)','High-Powered','[“+2CD Dam”,”-2 Rate”]','2','3','75'),
('Triple','Triple Barrel','[“+1 Rate”]','2','16','143'),
('Quad','Quad Barrel','[“+2 Rate”]','2','20','218'),
('Large','High Capacity','[“+1 Rate”,”Gain Unreliable”]','5','1','-3'),
('Quick-Eject','Quick','[“Gain Reliable”]','5','0','8'),
('Large Quick-Eject','Quick High Capacity','[“+1 Rate”]','5','1','23'),
('Comfort (Small Guns)','Comfort','[“Lose Inaccurate”]','4','0','6'),
('Sharpshooter’s','Sharpshooter’s','[“Lose Inaccurate”,”Gain Piercing 1”]','4','0','10'),
('Full (Small Guns)','','[“Gain Two-Handed”,”Lose Inaccurate”]','3','1','10'),
('Full (Energy Weapons)','','[“Gain Piercing 1”,”Lose Close-Quarters”]','3','1','15'),
('Marksman’s','Marksman’s','[“Gain Two-Handed”,”Lose Inaccurate”,”Gain Accurate”,”Lose Close-Quarters”]','3','2','20'),
('Recoil Compensating (Small Guns, Energy Weapons)','Recoil Compensated','[“Gain Two-Handed”,”Lose Inaccurate”,”+1 Rate”,”Lose Close-Quarters”]','3','2','3'),
('Recoil Compensating (Junk Jet, Cryolator)','Recoil Compensated','[“+1 Rate”]','3','2','40'),
('Standard','','[“Gain Two-Handed”,”Lose Inaccurate”,”Lose Close-Quarters”]','3','1','10'),
('Reflex (Small Guns, Energy Weapons, Cryolator)','Tactical','[“May re-roll hit location die”]','6','0','14'),
('Reflex (Gatling Laser)','Tactical','[“Lose Inaccurate”]','6','1','169'),
('Short Scope (Small Guns, Energy Weapons)','Scoped','[“Gain Accurate”]','6','1','11'),
('Long Scope','Scoped','[“Gain Accurate”,”+1 Range”]','6','1','29'),
('Short Night Vision','Night Vision','[“Gain Accurate”,”Gain Night Vision”]','6','1','38'),
('Long Night Vision','Night Vision','[“Gain Accurate”,”Gain Night Vision”,”+1 Range”]','6','1','50'),
('Recon','Recon','[“Gain Accurate”,”Gain Recon”]','6','1','59'),
('Gunner (Junk Jet)','Tactical','[“May re-roll hit location die”,”Lose Inaccurate”]','6','1','5'),
('Gunner (Minigun)','Tactical','[“Lose Inaccurate”]','6','1','68'),
('Scope','Scoped','[“Gain Accurate”]','6','6','143'),
('Night Vision','Night Vision','[“Gain Accurate”,”Gain Night Vision”]','6','6','248'),
('Targeting Computer','Targeting','[“When you Aim at a target,the target does not benefit form being in cover,and the bonus for aiming applies to the next attack on any subsequent turn during the scene”]','6','7','293'),
('Bayonet','Bayoneted','[“Add Bayonet weapon”]','7','2','10'),
('Compensator','Compensated','[“Lose Inaccurate”]','7','1','15'),
('Muzzle Break','Muzzled','[“Lose Inaccurate”,”+1 Rate”]','7','1','30'),
('Suppressor','Supressed','[“Gain Suppressed”]','7','2','45'),
('Beam Splitter (Energy Weapons)','Scattered','[“-1CD Dam”,”Gain Spread”,”Gain Inaccurate”,”-1 Rate”,”-1 Range”]','7','1','15'),
('Beam Focuser (Energy Weapons)','Focused','[“+1 Range”,”Gain Piercing 1”]','7','1','20'),
('Gyro Compensating Lens','Targeting','[“+1 Rate”,”Lose Inaccurate”]','7','1','25'),
('Electric Signal Carrer Antennae','Electrified','[“7CD Dam”,”Dam Type = Energy”,”Gain Radioactive”]','7','0','30'),
('Signal Repeater','Automatic','[“+2 Rate”,”Gain Burst”,”Lose Blast”]','7','0','60'),
('Electrification Module','Electrified','[“Gain Vicious”,”Dam Type = Energy”]','7','1','70'),
('Ignition Module','Flaming','[“Gain Persistent(Energy)”]','7','1','130'),
('Shredder','Bayoneted Shredding','[“Add Shredder Bayonet weapon”]','7','5','5'),
('Stabilizer','Muzzled','[“Gain Piercing 1”]','7','2','60'),
('Full Capacitors','High Capacity','[“Gain Vicious”]','8','0','37'),
('Capacitor Boosting Coil','Max Capacity','[“+1CD Dam”,”Gain Vicious”]','8','2','82'),
('Beta Wave Tuner (Energy Weapons)','Incendiary','[“Gain Persistent”]','8','0','30'),
('Beta Wave Tuner (Gatling Laser)','Incendiary','[“Gain Persistent”]','8','1','57'),
('Boosted Capacitor (Energy Weapons)','Boosted','[“+1CD Dam”,”-1 Rate”]','8','0','35'),
('Boosted Capacitor (Gatling Laser)','Boosted','[“+1CD Dam”]','8','1','94'),
('Photon Exciter (Energy Weapons)','Excited','[“Gain Vicious”]','8','0','30'),
('Photon Exciter (Gatling Laser)','Excited','[“Gain Vicious”]','8','1','19'),
('Photon Agitator (Energy Weapons)','Agitated','[“+1CD Dam”,”Gain Vicious”]','8','1','35'),
('Photon Agitator (Gatling Laser)','Agitated','[“+1CD Dam”,”Gain Vicious”]','8','3','132'),
('Three-Crank','Three-crank','[“+1CD Dam”,”+1 Ammo/Atk”]','8','0','4'),
('Four-Crank','Four-crank','[“+2CD Dam”,”+2 Ammo/Atk”]','8','1','8'),
('Five-Crank','Five-crank','[“+3CD Dam”,”+3 Ammo/Atk”]','8','1','12'),
('Six-Crank','Six-crank','[“+4CD Dam”,”+4 Ammo/Atk”]','8','2','16'),
('Deep Dish','Long','[“+1CD Dam”,”+1 Range”]','9','2','72'),
('Napalm','Napalmer','[“+1CD Dam”]','10','7','59'),
('Large (Flamer)','High Capacity','[“+1 Rate”]','11','3','28'),
('Huge (Flamer)','Max Capacity','[“+2 Rate”]','11','6','34'),
('Compression','Compressed','[“+1CD Dam”]','12','0','22'),
('Vaporization','Vaporizing','[“+1CD Dam”,”Gain Vicious”]','12','0','47'),
('Beam Focuser (Gatling Laser)','Focused','[“Gain Piercing 1”,”+1 Range”]','12','0','22'),
('Serrated (Sword)','Serrated','[“Gain Persistent”]','13','0','25'),
('Serrated (Knife)','Serrated','[“+1CD Dam”,”Gain Persistent”]','13','0','12'),
('Serrated (Machete)','Serrated','[“+2CD Dam”,”Gain Persistent”]','13','0','12'),
('Serrated (Switchblade)','Serrated','[“+1CD Dam”,”Gain Persistent”]','13','0','12'),
('Electrified','Electrified','[“+1CD Dam”,”Dam Type = Energy”]','13','0','50'),
('Electrified Serrated','Electrified Serrated','[“+1CD Dam”,”Dam Type = Energy”,”Gain Persistent(Physical)”]','13','0','75'),
('Stun Pack','Stunning','[“+2CD Dam”,”Dam Type = Energy”,”Gain Stun”]','13','0','100'),
('Stealth','Stealth','[“+1CD Dam”,”Gain Persistent”,”+2CD Dam on Sneak Attacks”]','13','0','18'),
('Curved','Curved','[“+1CD Dam”,”Spend 2AP on successful attack to disarm opponent”]','13','1','15'),
('Extended','Extended','[“+1CD Dam”,”Gain Persistent”]','13','3','25'),
('Extra Flame Jets','Searing','[“+1CD Dam”,”Gain Persistent”]','13','1','100'),
('Extra Claw','Large','[“+1CD Dam”,”Spend 2AP on successful attack to disarm opponent”]','13','2','22'),
('Barbed (Bat)','Barbed','[“Gain Piercing 1”]','14','0','5'),
('Barbed (Pool Cue)','Barbed','[“+1CD Dam”,”Gain Piercing 1”]','14','1','13'),
('Barbed (Cane)','Barbed','[“+1CD Dam”,”Gain Piercing 1”]','14','0','3'),
('Spiked (Bat)','Spiked','[“+1CD Dam”,”Gain Piercing 1”]','14','1','7'),
('Spiked (Board)','Spiked','[“+1CD Dam”,”Gain Piercing 1”]','14','1','6'),
('Spiked (Lead Pipe)','Spiked','[“+1CD Dam”,”Gain Piercing 1”]','14','1','4'),
('Spiked (Rolling Pin, Cane)','Spiked','[“+1CD Dam”,”Gain Piercing 1”]','14','0','3'),
('Spiked (Boxing Glove, Knuckles)','Spiked','[“Gain Piercing 1”]','14','0','3'),
('Sharp (Bat)','Sharp','[“+1CD Dam”,”Gain Persistent”]','14','1','7'),
('Sharp (Pool Cue, Rolling Pin)','Sharp','[“+1CD Dam”,”Gain Persistent”]','14','0','3'),
('Sharp (Knuckles)','Sharp','[“Gain Persistent”]','14','0','3'),
('Chain-Wrapped','Chain-wrapped','[“+2CD Dam”]','14','1','10'),
('Bladed (Bat)','Bladed','[“+2CD Dam”,”Gain Persistent”]','14','2','12'),
('Bladed (Board)','Bladed','[“+2CD Dam”,”Gain Persistent”]','14','2','10'),
('Bladed (Tire Iron)','Bladed','[“+1CD Dam”,”Gain Persistent”]','14','1','12'),
('Bladed (Knuckles)','Bladed','[“+1CD Dam”,”Gain Persistent”]','14','0','5'),
('Puncturing (Board)','Puncturing','[“+2CD Dam”,”Gain Piercing 1”]','14','1','9'),
('Puncturing (Pipe Wrench)','Puncturing','[“+2CD Dam”,”Gain Piercing 1”]','14','1','13'),
('Puncturing (Sledgehammer)','Puncturing','[“+1CD Dam”,”Gain Piercing 1”]','14','5','18'),
('Puncturing (Boxing Glove, Knuckles)','Puncturing','[“+1CD Dam”,”Gain Piercing 1”]','14','0','4'),
('Puncturing (Power Fist)','Puncturing','[“+2CD Dam”,”Gain Piercing 1”]','14','1','45'),
('Heavy (Lead Pipe)','Heavy','[“+2CD Dam”]','14','2','11'),
('Heavy (Pipe Wrench)','Weighted','[“+2CD Dam”]','14','7','12'),
('Heavy (Sledgehammer)','Heavy','[“+2CD Dam”]','14','9','30'),
('Hooked','Hooked','[“+1CD Dam”,”Spend 2AP on successful attack to disarm opponent”]','14','0','9'),
('Extra Heavy','Heavy','[“+3CD Dam”]','14','7','22'),
('Electrified','Shock','[“+2CD Dam”,”Dam Type = Energy”]','14','0','15'),
('Stun Pack (Baton)','Stunning','[“+3CD Dam”,”Dam Type = Energy”,”Gain Stun”]','14','0','30'),
('Stun Pack (Super Sledge)','Stunning','[“+2CD Dam”,”Dam Type = Energy”,”Gain Stun”]','14','0','360'),
('Heating Coil (Super Sledge)','Heated','[“+1CD Dam”,”Dam Type = Energy”]','14','0','180'),
('Heating Coil (Power Fist)','Heated','[“+2CD Dam”,”Dam Type = Energy”]','14','0','100'),
('Lead Lining','Lead-lined','[“+2CD Dam”]','14','1','7'),
('Overcharged','Overcharged','[“+1CD Dam”,”Gain Unreliable”]','14','0','20'),
('Long (M60, M79, Broadsider)','Long','[“+1 Range”]','2','2','40'),
('Caustic','Caustic','[“+1CD Dam”]','10','2','30'),
('Large Ampoule','High Capacity','[“+1 Rate”]','11','2','22'),
('Large Vial','Max Capacity','[“+3 Rate”]','11','4','40'),
('Fusion (Alien Blaster)','Converted','[“3CD Dam”,”-1 Rate”,“Ammo =Fusion Cell”]','5','0','21'),
('Capacitor Mk III','Mk III','[“+1CD Dam”,”+1 Ammo/Atk”]','8','0','4'),
('Capacitor Mk IV','Mk IV','[“+2CD Dam”,”+2 Ammo/Atk”]','8','1','8'),
('Capacitor Mk V','Mk V','[“+3CD Dam”,”+3 Ammo/Atk”]','8','1','12'),
('Capacitor Mk VI','Mk VI','[“+4CD Dam”,”+4 Ammo/Atk”]','8','2','16'),
('Light','Fluted','[“+2CD Dam”,”Lose Blast”]','2','3','30'),
('Multi Shot Canister','Repeating','[“+1 Rate”,”Gain Inaccurate”]','1','1','45'),
('M79 Launcher','Converted','[“+1 Range”,”Ammo=40mm Grenades”]','1','0','3'),
('Crystallizing','Crystallized','[“+2CD Dam”,”+1 Range”,”-1 Rate”,”Lose Stun”,”Lose Unreliable”]','2','5','40'),
('Fusion (Cryolator)','Converted','[“2CD Dam”,”-1 Rate”,”Ammo = Fusion Cell”]','5','0','21'),
('Barbed Harpoon','Barbed','[“Gain Vicious”,”Gain Persistent”]','5','0','21'),
('Flechette Darts','Tiny','[“Gain Spread”,”-1 Range”]','5','0','15'),
('Recoil Compensating (Harpoon Gun)','Recoil Compensated','[“+1 Rate”]','3','15','45'),
('Gunner (Harpoon Gun)','Tactical','[“May re-roll hit location die”,”Lose Inaccurate”]','6','0','17'),
('Short Scope (Harpoon Gun)','Scoped','[“Gain Accurate”]','6','1','28'),
('Armor Piercing','AP','[“Gain Piercing 1”]','1','0','3'),
('Armor Piercing Automatic','AP Auto','[“-1CD Dam”,+2 Rate”,”Gain Piercing 1”,”Gain Inaccurate”]','1','1','40'),
('Hardened Automatic','Hardened Auto','[“+2 Rate”,”Gain Inaccurate”]','1','2','58'),
('Rapid Automatic','Rapid','[“-1CD Dam”,”+3 Rate”,”Gain Inaccurate”]','1','2','58'),
('Calibrated Powerful','Calibrated Powerful','[“+2CD Dam”,”Gain Vicious”]','1','3','68'),
('Powerful Automatic','Powerful Auto','[“+1CD Dam”,”+2 Rate”,”Gain Inaccurate”]','1','4','88'),
('Hardened Piercing Auto','Hardened AP Auto','[“+2 Rate”,”Gain Piercing 1”,”Gain Inaccurate”]','1','3','78'),
('9mm Receiver','9mm','[“3CD Dam”,”+1 Rate”,”Ammo = 9mm”]','1','-1','10'),
('Gamma Wave Emitter (Energy Weapons)','Fiery','[“+1CD Dam”,”Gain Persistent”]','8','1','14'),
('Gamma Wave Emitter (Gatling Laser)','Fiery','[“+1CD Dam”,”Gain Persistent”]','8','3','169'),
('Maximized Capacitor (Energy Weapons)','Maximized','[“+2CD Dam”]','8','1','17'),
('Maximized Capacitor (Gatling Laser)','Maximized','[“+2CD Dam”]','8','3','207'),
('Boosted Photon Agitator (Energy Weapons)','Boosted Agitated','[“+2CD Dam”,”Gain Vicious”]','8','1','20'),
('Boosted Photon Agitator (Gatling Gun)','Boosted Agitated','[“+2CD Dam”,”Gain Vicious”]','8','5','244'),
('Boosted Gamma Wave Emitter (Energy Weapons)','Boosted Firey','[“+2CD Dam”,”Gain Persistent”]','8','1','23'),
('Boosted Gamma Wave Emitter (Gatling Laser)','Boosted Firey','[“+2CD Dam”,”Gain Persistent”]','8','5','282'),
('Overcharged Capacitor (Energy Weapons)','Overcharged','[“+3CD Dam”]','8','1','42'),
('Overcharged Capacitor (Gatling Laser)','Overcharged','[“+3CD Dam”]','8','5','319'),
('Improved Long','Improved Long','[“+1CD Dam”,”Lose Close Quarters”,”+1 Range”]','2','1','15'),
('Improved Automatic','Improved Auto','[“Gain Burst”,”Gain Inaccurate”,”Lose Close Quarters”,”+1 Range”,”+1 Rate”]','2','1','18'),
('Improved Sniper','Improved Charging','[“+3CD Dam”,”Lose Close Quarters”,”+1 Range”,”-1 Rate”]','2','1','21'),
('Improved Splitter','Improved Scattergun','[“Gain Spread”,”Gain Inaccurate”]','2','1','25'),
('Amplified Beam Splitter','Improved Scattered','[“Gain Spread”,”-1 Rate”,”-1 Range”]','7','1','15'),
('Fine-tuned Beam Focuser','Improved Focused','[“+1 Range”,”Gain Accurate”]','7','1','18'),
('Quantum Gyro-Compensating Lens','Improved Targeting','[“+2 Rate”,”Lose Inaccurate”]','7','1','21'),
('Heavy','','[“+1CD Dam”,”Gain Vicious”]','2','3','135'),
('Long (Auto Grenade Launcher)','Long','[“+1 Range”]','2','2','45'),
('25mm Grenade','25mm','[“4CD Dam”,”+2 Rate”,”Ammo = 25mm Grenade”]','1','3','135'),
('Speedy','','[“+2 Rate”]','1','1','35'),
('Long (Gatling Gun)','Long','[“+1 Range”]','2','2','158'),
('Comfort (Gatling (Plasma) Gun)','Comfort Grip','{“Lose Recoil (6)”}','4','3','90'),
('Extra-Large Magazine','','[“+1 Rate”,”Gain Unreliable”]','5','2','28'),
('Front Sight Ring','Sighted','[“Lose Inaccurate”]','6','2','158'),
('Large Bayonet','Bayoneted','[“Add Large Bayonet weapon”]','7','5','18'),
('Ported (Gatling Plasma)','Ported','[“Lose Inaccurate”]','2','6','81'),
('Reflex (Gatling Plasma)','Sighted','[“May re-roll hit location die”]','6','2','50'),
('Beam Splitter (Gatling Plasma)','Scattered','[“Gain Spread”]','12','3','20'),
('Beam Focuser (Gatling Plasma)','Focused','[“+1 Range”]','12','4','41'),
('Tri-Barrel (Gauss Minigun)','Triple Barrel','[“+1 Rate”]','2','4','91'),
('Penta-Barrel','Penta Barrel','[“-1CD Dam”,”-1 Range”,”+2 Rate”]','2','12','182'),
('Tesla Coil Capacitor','Tesla Capacitor','[“Energy Damage”]','8','8','91'),
('Tesla Coil Dynamo','Tesla Dynamo','[“Energy Damage”,”+1 Rate”]','8','12','136'),
('Calibrated','','[“Gain Vicious”]','8','3','140'),
('Pulse','Pulse','[“Gain Surge”]','8','3','70'),
('High Speed Electrode','Rapid','[“+1 Rate”]','8','3','105'),
('Long (Plasma Caster)','','[“+1 Range”]','2','5','128'),
('Compound','Compound','[“+1CD Dam”,”-1 Rate”,”Lose Recoil (6)”]','15','1','30'),
('Iron','','[“+1 Range”]','6','1','10'),
('Glow','Glow-Sighted','[“+1 Range”,”Gain Accurate”]','6','1','15'),
('Heavy','Heavy','[“+1CD Dam”]','15','1','30'),
('Repeating','Repeating','[“+1 Rate”,”Lose Slow-Load”]','15','2','75'),
('Multiple Launch','Peppered','[“-1CD Dam”,”Gain Ammo-Hungry (3)”,”Gain Spread”]','15','4','60'),
('Electrified (Assaultron Blade, Auto Axe)','Electrified','[“+1CD Dam”,”Dam Type = Energy”]','13','0','50'),
('Burning','Burning','[“Dam Type = Energy”,”Gain Persistent”]','13','0','50'),
('Poisoned','Toxic','[“Gain Persistent (Poison)”]','13','0','50'),
('Turbo','Turbo','[“Double CD for AP spent to increase damage”]','13','2','50'),
('Dual Bar','Dual','[“+2CD Dam”]','13','1','30'),
('Bow Bar','Bow Bar','[“Gain Piercing 1”]','13','2','45'),
('Long Bow Bar','Long Bow Bar','[“Gain Persistent”]','13','3','60'),
('Flamer','Flaming','[“+1CD Dam”,”Dam Type = Energy”]','12','2','90'),
('Liquid Nitrogen','Sub-Zero','[“+1CD Dam”,”Gain Piercing 1”]','10','8','80'),
('Compressed Tubing','Calibrated','[“Lose Inaccurate”]','2','1','28'),
('Wide Diffusion','Spray','[“Gain Burst”,”Gain Unreliable”]','12','2','65'),
('Aerosolizer','Vaporizing','[“Gain Spread”,”Gain Unreliable”]','12','2','65'),
('Bladed Exhaust','Battle','[“+1CD Dam”,”Gain Close Quarters”]','12','1','65'),
('Secure','Secure','[“Lose Unreliable”]','1','0','0'),
('Powered','Powered','[“+2CD Dam”,”Both Physical and Energy”]','1','0','0'),
('Aerodynamic','Aerodynamic','[“+1CD Dam”,”Gain Vicious”]','2','0','0'),
('Shocking Coils','Surging','[“+2CD Dam”,”Both Physical and Energy”]','14','0','100'),
('Extended','Extended','[“+1 Range”]','2','1','20'),
('Tactical','Tactical','[“Lose Inaccurate”]','4','0','28'),
('Snap','Double Action','[“+1 Rate”]','2','0','143'),
('3-Shot Chamber','3-Shot','[“+2 Rate”]','2','8','218'),
('6-Shot Chamber','6-Shot','[“+3 Rate”,”Gain Unreliable”]','2','10','250'),
('Balanced','Balanced','[“Gain Accurate”,”Gain Reliable”]','3','10','250'),
('Shotgun Receiver','Shotgun','["5CD Dam","Gain Spread","Gain Unreliable","Gain Slow Load"]','1','0','20'),
('Shock Mod','Shock','[“+2CD Dam”,”Dam Type = Energy”]','13','0','15'),
('Stun Mod','Stun','[“+3CD Dam”,”Gain Stun”,”Dam Type = Energy”]','13','0','30');